services:
  service1:
    build: ./srv1/
    container_name: service1
    command: python3 srv1.py
    

  service2:
    build: ./srv2/
    container_name: service2
    command: dotnet run
    
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - name: web
        target: 8198
        published: "8198"
      
      - name: test
        target: 8197
        published: "8197"
  
   
networks:
  default:
    name: net 